server:
  port: 8080

spring:
  application:
    name: auth
  cloud:
    loadbalancer:
      enabled: false

management:
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka/

store:
  jwt:
    issuer: "In5pEr"
    secretKey: "nPeHcqPFhcHhy9fIEgjYSEWBQaNhVtyYKqo1jR97H23x75qI8Tj33c5AZumnPsoF8QRLjxfC5bgKoK5uHqNmSffMjm2qQXMghW4ju4zrMxAx9Dlpq83HGgo05H8QEuue"
    duration: 31536000000 # 365 days in miliseconds
